### ISSUE TITLE
Reliability and ACKs

### ISSUE THREAD

**Issue by Artaud** [dillpixel/fitbit-asap#2]
Hi @daveyjones, this is more of a suggestion, something I'd need and would be willing to work on.

From the [documentation](https://dev.fitbit.com/build/reference/device-api/messaging/#interface-messageevent) on the MessageSocket.send() in the Fitbit SDK, I understood that the peer messaging channel between companion and watch is not 100% reliable, quoting:

> There is no message loss while the endpoints are connected. This means that there are no gaps. A message is either successfully transmitted, in order, or it failed to be delivered because the channel has been closed (endpoints disconnected). After a failure, the channel is closed and no messages can be exchanged until a new channel is opened. **It is possible, however, that the last messages sent before disconnection will never be delivered.**

If I understand that correctly, it means I can never trust _messaging.peerSocket.readyState_.

I need a 100% reliable channel, which would mean implementing ACK message queue. Is this something that you would like to see in this library? I'm currently going to implement this in my app anyway, so I figured it might as well go into a public module.

I think it would be a really nice fit to add acks to your messaging library.

**Comment by daveyjones** [comment]
@Artaud Thanks for your interest in the project!

Given the fragility of the Bluetooth connection, the Messaging API should really only be used if a message *must* be sent in real time in order to achieve the desired functionality. (This should always be implemented with appropriate messaging for instances when no connection is available.) All other messaging should probably be handled via the File Transfer API, which is now [bi-directional](https://dev.fitbit.com/blog/2018-12-17-its-time-to-exercise-with-fitbit-os-3/#file-transfer-upload-api).

If we switch to using the File Transfer API instead of the Messaging API, we can ensure 100% reliability with even fewer lines of code. I think that's the direction I'd like to move in. What are your thoughts?

**Comment by Artaud** [comment]
Ouch, sorry, I completely forgot about this thread.
Well I don't really think that the File Transfer API and Messaging API are for the same use case. As you said, if the message has to be sent in real time, messaging API is a must.

The File Transfer API doesn't have any timeframe in which the message could be guaranteed to deliver. Not sure if it's a minority use case, but I feel that the Messaging API would benefit from a similar simplifying wrapper as this ASAP lib, which would however need to implement acks to be reliable.

I also think that what you started here goes more in the direction of the messaging API (you are already using it, and also do persist your queue to filesystem, which the File transfer api wouldn't need) and switching to File transfer API would essentially be a completely new project.

Frankly - I'm not even sure if the File Transfer API would need any wrapper at all - seems simple enough to me as it is...

**Comment by daveyjones** [comment]
Hi @Artaud—this is a great conversation. Thanks for taking the time. Another thing I hadn't considered with the File Transfer API is that the outbox could get backed up—e.g. if another app queues up a bunch of large files, it could cause ASAP messages to be delayed more than necessary (which goes against the "as soon as possible" concept).

That being said, the File Transfer API may still have a place in the ASAP library at some point—e.g. to handle messages that exceed the maximum size allowed by the Messaging API. But that's probably another topic.

I like the idea of ACKs. To maintain the simplicity and elegance of the module, I think this is something that should occur behind the scenes (i.e. it wouldn't change the API at all—messages would simply be re-sent if earlier attempts are not acknowledged).

I'm thinking the way it would work is that once a message is received, an acknowledgement would be sent. If the acknowledgement is not received by the sender, then the message will be attempted again until acknowledgment is received. On the receiving side, once a message is received, this will be recorded so that if the same message happens to be received again (e.g. if a connection issue prevents the acknowledgment from being received by the original sender), the `onmessage` event would not fire again for the same message.

**Comment by Artaud** [comment]
I agree with you. Let's outline the implementation proposal.

The API should be kept minimal. I really like what you already did, so as far as I am concerned, let's just keep it at:
* asap.send(message, options)
* asap.onmessage = message => { ... }

ACKs should work as you said. Each message would have a unique incrementing ID. Since the order of messages is guaranteed to be preserved by the Messaging API (according to [the docs](https://dev.fitbit.com/build/reference/device-api/messaging/#method-send)), we only need to store the last message ID on the receiving side.
When a message is received, we need to check if it's an ACK or a real message.
- If it's an ACK, we don't trigger _onmessage_.
- If it's a message, the message ID will be compared to the last stored ID. 
	- If the received ID is higher, we send an ACK and trigger _onmessage_. (Case: the message has been delivered for the first time) 
	- If the received ID is same or lower, we send an ACK, but don't trigger _onmessage_. (Case: the message was delivered previously but ACK was lost.)

As it stands now, your message object is:
```
  const data = {
    _asap_id: Math.floor(Math.random() * 10000000000), // Random 10-digit number
    _asap_created: now,
    _asap_expires: now + options.timeout,
    _asap_status: "sending",
    _asap_message: message
  }
```
I propose adding a type enum like
```
var _asap_type = {
  MESSAGE: 1,
  ACK: 2
};

```

The receiving side is clear.

The sending side would be a little more tricky as we need to keep all messages in the queue until we get an ACK for them, or until a (global or per-message?) timeout.
We also need to prevent out of memory should the messages pile up, so we need to decide how will we approach pruning the queue when we reach a certain memory limit:
- start by deleting oldest messages?
- start by deleting oldest messages but keep messages smaller than X?
- other ideas?

The sending side would periodically need to send the messages until it gets an ACK back, or until the message expires. Question is, what is a good interval to send the messages? Can we flood the Messaging API?

What to do with the queue persistence to filesystem? Should we leave it in to preserve the queue across app starts? Wouldn't that cause unexpected behaviour?

And just on a sidenote - have you considered using Typescript for this project? There's a great typings library for Fitbit at https://github.com/SergioMorchon/fitbit-sdk-types and the maintainer is super responsive.

**Comment by Artaud** [comment]
I couldn't sleep tonight and I thought about this a little more and got a few ideas.

1) When we have more than one message in queue, do we need to wait for its ACK before sending another message? For a simple implementation, we could. However, to speed up the protocol, I think there is another way to do it.
Since the order of messages is guaranteed to be preserved across the Messaging API, I think we don't have to wait for ACKs and in a normal state, we can assume that we will receive them for each message.
Whenever we don't get an ACK, i.e. we have to resend any message, we could switch the whole wrapper to a, let's say, "connecting" state, in which we will freeze the queue and just attempt to send the first message until we get an ack. When the first message is successfully ACKed, we can switch back to "sending" state.

2) How to handle onerror from Messaging API? This could be tied to the previous proposal - whenever we get an onerror, we switch to "connecting" state. 

3) How often can we send messages?
I think we need to decide what will happen in the following extreme testcase:
```
while (true) {
	asap.send(msg)
}
```

4) Finally, I think it might be pretty useful to have our own onerror callback. As the underlying API (or the physical reality below it) is unreliable, we too would be probably lying to ourselves if we claimed that our API would be 100% reliable. Since it can happen that we lose connection, we should probably signal it somehow. 
I propose adding an onerror callback that triggers if the connection is cut for more than X seconds/minutes. I.e. when we are in a "connecting" state for X time, we'll fire onerror, but keep trying to connect.




It may be useful to somehow systematize our efforts at this point.... :)

**Comment by daveyjones** [comment]
@Artaud Thanks again for all the thought you've put into this.

>Each message would have a unique incrementing ID.

That makes sense. We'll need to create a `get_next_id()` function that returns the ID of the last element in the queue + 1.

Also, I'm not sure we really need to define an enumerated type. I think a simple `_asap_ack` boolean is sufficient. So the new data object could look like this:

```
const data = {
  _asap_id: get_next_id(),
  _asap_created: now,
  _asap_expires: now + options.timeout,
  _asap_status: "sending",
  _asap_message: message, // If this is a message
  _asap_ack: true // If this is an ACK
}
```

>The sending side would be a little more tricky as we need to keep all messages in the queue until we get an ACK for them, or until a (global or per-message?) timeout.

We can continue to re-send the message until (1) we receive an ACK or (2) the `_asap_expires` lapses. If `_asap_expires` does lapse, then we should fire an `onerror` callback as you've suggested.

>We also need to prevent out of memory should the messages pile up, so we need to decide how will we approach pruning the queue when we reach a certain memory limit:

I think this is a separate issue and can be handled independently of the ACK functionality, so I've opened issue #3 to cover this.

>The sending side would periodically need to send the messages until it gets an ACK back, or until the message expires. Question is, what is a good interval to send the messages? Can we flood the Messaging API?

We should follow the recommendations outlined [here](https://dev.fitbit.com/build/guides/communications/messaging/#buffering-data).

>*The `bufferedAmount` property can be used to determine how much data currently resides within the buffer. By subscribing to the `onbufferedamountdecrease` event, the sending of data can be resumed once there is available space in the buffer.*

However, if we're waiting for ACKs before sending the next message, I doubt we'll ever overflow the buffer. The question is, how long should we wait for the ACK before making another attempt? I think we just pick something reasonable to start with and tune from there. Maybe start with 5 seconds?

>What to do with the queue persistence to filesystem? Should we leave it in to preserve the queue across app starts? Wouldn't that cause unexpected behaviour?

Yes, the queue needs to persist to the filesystem. Otherwise, all queued messages would be lost when you exit the app.

>When we have more than one message in queue, do we need to wait for its ACK before sending another message?

For now, I think we should wait to receive an ACK before sending the next message. I think it could be useful if we can guarantee that messages will always be delivered in the order they're queued. Maybe we can consider speed optimizations in future iterations.

>How to handle onerror from Messaging API?

Actually, I don't think we really need to do anything—if there's an error, then an ACK will never be received and another attempt will be made automatically.

>How often can we send messages?

As mentioned above, we can follow the recommendations outlined [here](https://dev.fitbit.com/build/guides/communications/messaging/#buffering-data).

>Finally, I think it might be pretty useful to have our own onerror callback.

I agree, but I don't think we should fire the `onerror` callback if the connection is lost for X amount of time. ASAP implies that messages can't always be sent in real time—the promise is simply to send them as soon as possible. Since delay is inherent to the system, I don't think it makes sense to say that an error has occurred simply because the system has been disconnected for a certain amount of time. However, if a specific message expires before we're able to send it, then I think it makes sense to call the `onerror` callback (so the application can handle it).

>It may be useful to somehow systematize our efforts at this point.... :)

Agreed! I think the most important thing here is to not try to solve all the problems at once. Whenever possible, we should spin ideas off into separate issues (which I've already done with issue #3). There may be other issues we can spin off, keeping the focus of this thread on ACK functionality.

**Comment by Artaud** [comment]
Perfect. I agree with most of your answers, except:

> Yes, the queue needs to persist to the filesystem. Otherwise, all queued messages would be lost when you exit the app.

This is a point I'm not quite sure of. In some applications, it is desirable that the queue be cleared when the app exits. So I think we should either provide a flag for such behaviour (which I'm not a big fan of) or provide a method to clear the persisted queue.

And this might also be a spin-off issue handled separately. I've opened a new issue https://github.com/dillpixel/fitbit-asap/issues/4.

**Comment by daveyjones** [comment]
@Artaud I agree—and yes, I think this is something that should be spun off. I've added a comment to issue #4 on how we might implement this.
