### ISSUE TITLE
Provide a way to control queue persistence

### ISSUE THREAD

**Issue by Artaud** [dillpixel/fitbit-asap#4]
In some applications, it is desirable that the queue be cleared when the app exits. I think we should either provide a flag for such behaviour or provide a method to clear the persisted queue.

**Comment by daveyjones** [comment]
Great idea. I think we should handle this on a message-by-message basis using the existing `timeout` option. This way, you could have both persistent and non-persistent messages in the same app.

Currently, `timeout` can be an integer that represents the maximum amount of time a message can remain in the queue (in milliseconds). We could also allow `timeout` to be a string.
```
asap.send(message, {timeout: "session"})
```
Each time the app starts up, any messages with "session" timeouts would be removed from the queue before any communication occurs (since they expired at the end of the previous session).

Would this satisfy the use case you have in mind?

**Comment by Artaud** [comment]
That's a neat solution, I'm all for that. I'll submit a PR today for this and tomorrow for the ACKs if you agree?

**Comment by daveyjones** [comment]
Yes, sounds great!
