### ISSUE TITLE
What about I/O blocking?

### ISSUE THREAD

**Issue by Artaud** [dillpixel/fitbit-asap#6]
I'm thinking that there are way too many write/read operations on filesystem involved currently.

Right now, to send one message, we have two reads and one write on the sending side, and one read and one write on the receiving side.
That's for every message, and we always read and write the entire queue. The IO operations are synchronous, so there is a possibility of freezing the app if we have a larger queue.

Could we make the IO calls asynchronous?

**Comment by Artaud** [comment]
In a minimal scenario, we could also just persist the queue on unload and read it at app start.

**Comment by daveyjones** [comment]
I think persisting the queue on unload is an unnecessary risk. If reliability is the primary goal, then we want to make sure to persist the queue right away so that in any case (e.g. a crash) the queue is still in-tact.

Going along with issue #7, I think we simply need to write a test that queues up a large amount of messages and see what the timing of the IO operations looks like. That way we can know for sure whether it's a problem worth solving.

**Comment by Artaud** [comment]
I agree that it is a risk, as not only it may take longer than the unload event will permit, but also I found out that the unload event will often not be called at all.
I agree with the test, but was unable to make Jest running on this project :/
